using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CPT230Assignment05
{
    public partial class frmAssignment05 : Form
    {

        /* Marshall Westbrook
         * CPT-230-S73
         * Assignment05
         * Summer 2021
         * Rectangular Arrays + Maze
         */

        Label[,] maze = new Label[10, 10]; // maze array
        // Create empty whitelist for the path
        Boolean[,] whitelist = new bool[10, 10]; // whitelist array
        Random random = new Random();


        public frmAssignment05()
        {
            InitializeComponent();
        }


        public void frmAssignment05_Load(object sender, EventArgs e)
        {
            // Show message box with instructions before the maze is visible
            ShowInstructions();
            // Create 10 x 10 array for maze
            
            // Manually create path. This could be generated by an algorithim in the future
            CreatePath(whitelist);
            // Create Labels with event handlers on mouse over that send the cursor back to the starting position
            BuildMaze(maze, whitelist);

            // Creating Walls around Win button so the user can't cheat as easily
            PreventCheating();

        }

        private static void ShowInstructions()
        {
            // Show on program launch. Can also be displayed when start label is clicked
            MessageBox.Show("Instructions: \r\n Move your mouse through the maze without touching the black area.", "Assignment 5 Instructions");
        }




        // Creating each wall and giving them properties. inPanel is an optional parameter
        private void BuildWallLabels(Label l, Color wallBackColor, Color wallForeColor, Size wallSize, Point wallLocation, bool inPanel = true)
        {
            // Create label
            l = new Label();

            // Change background color
            l.BackColor = wallBackColor;
            // Change Foreground Color (text, if used)
            l.ForeColor = wallForeColor;
            // Change minimum size
            l.Size = wallSize;
            // Add event handler that sends mouse back to starting position
            l.MouseEnter += wall_Collision;
            // Set wall location
            l.Location = wallLocation;
            // Make sure wall is visible
            l.Visible = true;
            // Add text
            //l.Text = "wall"; // Option to add text here. Used this for testing
            // AutoSize is not actie. Autosize will create variance. In testing this made the walls invisible or halfway off the screen
            l.AutoSize = false;
            // Add Control to panel (this is done by default)
            if (inPanel == true)
            {
                pnlMain.Controls.Add(l);
            }
            // Adding Controls outside of panel to prevent cheating
            else
            {
                Controls.Add(l);
            }

        }


        // Creating the maze
        private void BuildMaze(Label[,] maze, Boolean[,] whitelist)
        {
            // Wall properties
            // Get the top left corner of the panel
            Point wallStart = pnlMain.Location;
            // Selected these colors from the default colors on a label. Reversed them for easier visibility
            Color wallBackColor = Color.FromName("ActiveCaptionText");
            Color wallForeColor = Color.FromName("Control");
            // Setting wall size based on the panel width divided by the column size and the panel height divided by row length.
            Size wallSize = new Size(pnlMain.Width / maze.GetLength(1), pnlMain.Height / maze.GetLength(0)); // Get the panel width and divide by the array column size. Do the same for height and rows.

            // Looping through each row
            for (int i = 0; i < maze.GetLength(0); i++)
            {
                // Looping through each column
                for (int j = 0; j < maze.GetLength(1); j++)
                {
                    // Build a wall if value is not true in whitelist
                    if (whitelist[i,j] == false)
                    {
                        // Get top left of panel
                        Point wallLocation = wallStart;
                        // Add the width of the wall size multiplied by the iteration in the column loop
                        wallLocation.X = (j * wallSize.Width);
                        // Add the height of the wall size multiplied by the iteration in the row loop
                        wallLocation.Y = (i * wallSize.Height);

                        // Create labels and give them properties
                        BuildWallLabels(maze[i, j], wallBackColor, wallForeColor, wallSize, wallLocation);
                    }
                }
            }
        }

        private void PreventCheating()
        {
            // Extra Wall Properties
            Color extraWallBackColor = Color.FromName("ActiveCaptionText");
            Color extraWallForeColor = Color.FromName("Control");
            Size extraWallSize = lblWin.Size;
            Point winButtonLocation = lblWin.Location;

            // Individual Locations for Left, Right, and Above the Win Label
            Point extraWallLocationLeft = winButtonLocation;
            extraWallLocationLeft.X -= (extraWallSize.Width);

            Point extraWallLocationRight = winButtonLocation;
            extraWallLocationRight.X += extraWallSize.Width;

            Point extraWallLocationAbove = winButtonLocation;
            extraWallLocationAbove.Y -= 14;

            // BuildWallLabels takes a Label type, but arrays of a type are created with null placeholders. These three null labels are
            // to pass into the same method. If this needed to be done more often, we should make the method more general to reduce the need for this.
            Label extraWallLeft = null;
            Label extraWallRight = null;
            Label extraWallAbove = null;

            // Call our buildwalls method with the custom locations outside of the panel.
            bool inPanel = false;
            BuildWallLabels(extraWallLeft, extraWallBackColor, extraWallForeColor, extraWallSize, extraWallLocationLeft, inPanel);
            BuildWallLabels(extraWallRight, extraWallBackColor, extraWallForeColor, extraWallSize, extraWallLocationRight, inPanel);
            BuildWallLabels(extraWallAbove, extraWallBackColor, extraWallForeColor, extraWallSize, extraWallLocationAbove, inPanel);
        }

        // Method for label event handlers. This was to make it clearer for me to understand which part to add to each label
        private void wall_Collision(object sender, EventArgs e)
        {
            // Call method that sends mouse back to starting point
            MouseToStart();
        }

        private void MouseToStart()

        {
            // Find panel top left corner
            Point startingpoint = pnlMain.Location;
            // Offset the starting point to make it in the center of the bottom of the panel (+ 10 pixels Y and -10 pixels X)
            startingpoint.Offset(pnlMain.Width/2 - 10,pnlMain.Height + 10);
            // set cursor location
            Cursor.Position = PointToScreen(startingpoint);
        }

        // Win condition is clicking the label
        private void lblWin_Click(object sender, EventArgs e)
        {
            // Show Message box. Mouse cursor shouldn't interact with mouse over events when this is open
            MessageBox.Show("You WON! Thanks for playing!", "You're a Winner!");
            // Add some color to the game. It's kinda boring without it!
            WallColors();



            // Optional: Exit program
            //Application.Exit();
        }


        public void WallColors()
        {
            // Loop through every label within the panel
            foreach (Label label in pnlMain.Controls)
            {
                // Create a new color
                Color myRgbColor = new Color();
                // Use random values that aren't too close to white
                myRgbColor = Color.FromArgb(random.Next(20, 256), random.Next(20, 256), random.Next(20, 256));
                // Set the backcolor values for the labels
                label.BackColor = myRgbColor;
            }

        }

        // Whitelist array for the path to winning.
        private static void CreatePath(bool[,] whitelist)
        {
            // Manually set this path. In the future this could be generated by an algorithim based on maze array size.
            whitelist[9, 4] = true;
            whitelist[8, 4] = true;
            whitelist[8, 3] = true;
            whitelist[8, 2] = true;
            whitelist[8, 1] = true;
            whitelist[7, 1] = true;
            whitelist[6, 1] = true;
            whitelist[6, 2] = true;
            whitelist[6, 3] = true;
            whitelist[6, 4] = true;
            whitelist[6, 5] = true;
            whitelist[6, 6] = true;
            whitelist[7, 6] = true;
            whitelist[7, 8] = true;
            whitelist[8, 6] = true;
            whitelist[8, 7] = true;
            whitelist[8, 8] = true;
            whitelist[6, 8] = true;
            whitelist[5, 8] = true;
            whitelist[4, 8] = true;
            whitelist[4, 7] = true;
            whitelist[4, 6] = true;
            whitelist[4, 5] = true;
            whitelist[4, 4] = true;
            whitelist[3, 4] = true;
            whitelist[3, 3] = true;
            whitelist[3, 2] = true;
            whitelist[3, 1] = true;
            whitelist[2, 1] = true;
            whitelist[1, 1] = true;
            whitelist[1, 2] = true;
            whitelist[1, 3] = true;
            whitelist[1, 4] = true;
            whitelist[1, 5] = true;
            whitelist[1, 6] = true;
            whitelist[1, 7] = true;
            whitelist[1, 8] = true;
            whitelist[0, 8] = true;
        }

        private void lblStart_Click(object sender, EventArgs e)
        {
            ShowInstructions();
        }
    }
}
